//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoSalon.WebUI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutoSalon.WebUI.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доваби.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добави нов автомобил.
        /// </summary>
        public static string Add_New_Cars {
            get {
                return ResourceManager.GetString("Add_New_Cars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Марка.
        /// </summary>
        public static string Brand {
            get {
                return ResourceManager.GetString("Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текстът трябва да е с дължина между 3 и 20 символа!.
        /// </summary>
        public static string Description_Val_Error_Message {
            get {
                return ResourceManager.GetString("Description_Val_Error_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мечтани автомобили.
        /// </summary>
        public static string Dream_Cars {
            get {
                return ResourceManager.GetString("Dream_Cars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Намери твоят мечтан автомобил.
        /// </summary>
        public static string Find_your_dream_car {
            get {
                return ResourceManager.GetString("Find_your_dream_car", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PS.
        /// </summary>
        public static string Horsepower_Initials {
            get {
                return ResourceManager.GetString("Horsepower_Initials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вносител.
        /// </summary>
        public static string Importer {
            get {
                return ResourceManager.GetString("Importer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мощност.
        /// </summary>
        public static string Power {
            get {
                return ResourceManager.GetString("Power", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добави в базата!.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Търси.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Избери вносител.
        /// </summary>
        public static string Select_Importer {
            get {
                return ResourceManager.GetString("Select_Importer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Година.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
    }
}
